dist: bionic
language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main
        key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
    packages:
      - clang-format-11
      - clang-11
      - g++-10

env:
  global:
    - CXX=g++10
    - CLANG_FORMAT=clang-format-11

  jobs:
    - L1D_PREF='no_l1d'
      L1I_PREF='no_l1i'
      L2C_PREF='no_l2c'
      LLC_PREF='no_llc'
      LLC_REP='drrip_llc'
      BPRED='bimodal'
    - L1D_PREF='next_line_l1d'
      L1I_PREF='next_line_l1i'
      L2C_PREF='ip_stride'
      LLC_PREF='next_line_llc'
      LLC_REP='lru_llc'
      BPRED='gshare'
    - L1D_PREF='va_next_line_l1d'
      L1I_PREF='no_l1i'
      L2C_PREF='kpcp'
      LLC_PREF='no_llc'
      LLC_REP='ship_llc'
      BPRED='hashed_perceptron'
    - L1D_PREF='no_l1d'
      L1I_PREF='no_l1i'
      L2C_PREF='next_line_l2c'
      LLC_PREF='no_llc'
      LLC_REP='srrip_llc'
      BPRED='perceptron'
    - L1D_PREF='no_l1d'
      L1I_PREF='no_l1i'
      L2C_PREF='spp_dev'
      LLC_PREF='no_llc'
      LLC_REP='lru_llc'
      BPRED='bimodal'
    - L1D_PREF='no_l1d'
      L1I_PREF='no_l1i'
      L2C_PREF='va_ampm_lite'
      LLC_PREF='no_llc'
      LLC_REP='lru_llc'
      BPRED='bimodal'
    - L1D_PREF='no_l1d'
      L1I_PREF='no_l1i'
      L2C_PREF='va_ip_stride'
      LLC_PREF='no_llc'
      LLC_REP='lru_llc'
      BPRED='bimodal'

before_script:
    - cat champsim_config.json | jq "setpath([\"ooo_cpu\", 0, \"branch_predictor\"]; \"$BPRED\") | setpath([\"L1I\", \"prefetcher\"]; \"$L1I_PREF\") | setpath([\"L1D\", \"prefetcher\"]; \"$L1D_PREF\") | setpath([\"L2C\", \"prefetcher\"]; \"$L2C_PREF\") | setpath([\"LLC\", \"prefetcher\"]; \"$LLC_PREF\") | setpath([\"LLC\", \"replacement\"]; \"$LLC_REP\") | setpath([\"CXX\"]; \"$CXX\") | setpath([\"CLANG_FORMAT\"]; \"$CLANG_FORMAT\")" > champsim_config_new.json
    - mv champsim_config_new.json champsim_config.json
    - ./config.sh champsim_config.json


jobs:
  - include:
      script:
        - make format-check

script:
  - make -j CXX=g++-10
  - make clean
  - make -j CXX=clang++-11
